original_repo: https://github.com/cecivieira/wids-valencia

volunteers_form: ""
mentors_form: ""
attendees_form: https://wids-valencia-2019.eventbrite.es

keywords: "conferencia, ciencia de datos, mujer, tecnología, Valencia, evento, marzo, UPV, MUGI, VLCTechHub"
title: "WiDS Valencia"
description: "WiDS Valencia tiene el objetivo de inspirar personas de todos los géneros para la Ciencia de Datos a partir de la divulgación de trabajo de mujeres científica de datos. Será celebrado en el 04 de marzo."
ogimage: "/assets/images/Cartel.png"

sass:
    sass_dir: assets/_sass
    style: compressed
