original_repo: https://github.com/VLCTechHub/widsvalencia2019

volunteers_form: "Elena M. Codonyer, Matea Jermanis, Marta Hernandez, Laura Porto, Andrea Naranjo"
mentors_form: ""
attendees_form: "https://www.eventbrite.es/e/333019017847"

keywords: "conferencia, ciencia de datos, mujer, tecnología, Valencia, evento,"
title: "WiDS Valencia"
description: "WiDS Valencia tiene el objetivo de inspirar a personas de todos los géneros para despertarles el interés por la Ciencia de Datos, a partir de la divulgación del trabajo de mujeres científicas de datos."
ogimage: "/assets/images/Cartel.png"

sass:
    sass_dir: assets/_sass
    style: compressed
